project_id = "xzupccxznjljzhddqenz"

[functions.generate-qr]
verify_jwt = true

[functions.verify-qr]
verify_jwt = true

[functions.register-face]
verify_jwt = true

[functions.verify-face]
verify_jwt = true

[functions.verify-proximity]
verify_jwt = true

[functions.secure-register-face]
verify_jwt = true

[functions.attendance-chatbot]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-update-user]
verify_jwt = true
